apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-db
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
{{ include "labels.db" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ .Values.name }}-db
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: {{ .Values.name }}-db
    spec: 
      containers:
      - name: {{ .Values.name }}-db
        envFrom: 
        - secretRef:
            name: {{ .Values.name }}-config
        image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:10-el8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: {{ .Values.name }}-db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Values.name }}-db-data
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-db