apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ .Values.name }}-db
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
{{ include "labels.db" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem