apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-db
labels:
{{ include "labels.db" . | indent 4 }}
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  sessionAffinity: None
  type: ClusterIP