apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-app
  labels:
{{ include "labels.app" . | indent 4 }}
spec:
  ports:
  - name: app-tcp
    protocol: TCP
    port: {{ .Values.network.port }}
    targetPort: {{ .Values.network.port }}
  selector:
    deployment: {{ .Values.name }}-app
  sessionAffinity: None
  type: ClusterIP
