{{- if and .Values.config.enabled .Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
{{ include "labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.config.data }}
  {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}