apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels" . | indent 10 }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP