{{- if .Values.routeEnabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  port:
    targetPort: input
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
{{- end }}